import os
# get the top level folder for this project
dir_path = os.path.dirname(os.path.realpath(__file__))

# define environment vaiables
class Config(object):
    # A random key generated by command:
    #   python -c 'import os; print(os.urandom(16))'
    # Variables to configure database
    USERNAME = 'ece1779_project'
    PASSWORD = 'ece1779_project_pass'
    HOSTNAME = 'ece1779-db.cr7yempg1jxm.us-east-1.rds.amazonaws.com'
    DATABASE = 'ece1779_project'
    # Top level folder path
    TOP_FOLDER = dir_path
    # aws credentials
    ACCESS_KEY_ID = 'AKIA5332NEH3HYA6KL2B'
    SECRET_KEY = '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'
    REGION = 'us-east-1'
