import os
# get the top level folder for this project
dir_path = os.path.dirname(os.path.realpath(__file__))

# define environment vaiables
class Config(object):
    # A random key generated by command:
    #   python -c 'import os; print(os.urandom(16))'
    # Variables to configure database
    USERNAME = 'ece1779_project'
    PASSWORD = 'ece1779_project_pass'
    HOSTNAME = 'ece1779-db.cr7yempg1jxm.us-east-1.rds.amazonaws.com'
    DATABASE = 'ece1779_project'
    
    # Top level folder path
    TOP_FOLDER = dir_path

    # aws credentials
    ACCESS_KEY_ID = 'AKIAIJK4UQ7KTGQZY4OQ'
    SECRET_KEY = '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'
    REGION = 'us-east-1'
